= Hugo Theme Component: Asciidoctor Skin

Adds a fully styled Asciidoctor Stylesheet to your Hugo site so all your pages will look amazing.

Designed to be included as a theme component to your Hugo site, so code id separated nicely and you don't have to worry so much about problems related to updates.


== Features
* Dark + Light-Mode
* Customisable in many ways
* Great predesign for
** typography
** content elments
** forms
** and a lot more


== Installation

==== 1. Clone this theme component to your `/themes` directory
[source]
----
git submodule add https://github.com/hugoseotheme/hugo-theme-component-asciidoctor-skin ./themes/hugo-theme-component-asciidoctor-skin
----

==== 2. Add this theme component to your list of themes inside your `config.(yaml|toml|json)` file
[source, toml]
----
theme = ["…", "hugo-theme-component-asciidoctor-skin", "…"]
----

==== 3. Import the styles into your themes main stylesheet
The styles are located inside the `/assets/asciidoctor-skin` directory in the theme component and are available inside that directory in your project root and other themes and theme components at the same place because of the way Hugo merges all its sources into one site when building.

So when you are writing your styles inside a subfolder of `assets` like `/assets/sass`, `/assets/scss`, `/assets/css` or `/assets/styles` you can import like so:

.In SASS
[source, sass]
----
@import ../asciidoctor-skin/import
----

.In SCSS
[source, scss]
----
@import '../asciidoctor-skin/import';
----

.In CSS
[source, css]
----
@import url('/asciidoctor-skin/import.min.css');
----


== Personalisation
=== with `SASS|SCSS`
Have a look into `_variables.scss` to get an idea of what you can change, also check out the files inside `mixins` and `functions` to see the available mixins and functions you can use.

=== with `CSS`
Once you added the stylesheet to your document you can see a list of all CSS custom properties in your browsers dev tools when you inspect the `html` node.
